application: turbo-ninja-client
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files : index.html
  upload: (.*?)
  
- url: /mobile
  static_files : mobile.html
  upload: (.*?)
  
- url: /img
  static_dir: img
  
- url: /res
  static_dir: res

- url: /vendor
  static_dir: vendor